- src/engine/Cache.class.js
> fix[cache]: #1014 - Properly split filename

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/migration/migration.service.js
- src/migration/migrationRules.js
- src/south/Modbus/Modbus.class.js
- src/south/Modbus/Modbus.class.spec.js
- src/south/Modbus/Modbus.schema.jsx
- src/south/Modbus/config/getOptimizedConfig.js
This feature allows to define an offset on the addresses of the points to be requested in order to be compatible with the JBus protocol. When using JBus, all the addresses are offset by -1, the addition of this new field avoids having to increment the addresses of all the points manually.
> feat(south-modbus): Modbus address offset (ON TOP OF #1128)

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/migration/migration.service.js
- src/migration/migrationRules.js
- src/south/Modbus/Modbus.class.js
- src/south/Modbus/Modbus.class.spec.js
- src/south/Modbus/Modbus.schema.jsx
This feature allows you to define the type of values to be read. By default with the Modbus protocol, the values of the HoldingRegister and InputRegister registers are stored as UInt16. But it is more and more common to see Modbus PLCs storing these values on 32 bits (signed or unsigned), and sometimes these values can be decimal numbers and not integers. In rarer cases the values may even be stored on 64 bits.
>  feat(south-modbus): Add possibility to specify the data type of a point (ON TOP OFF #1129)

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/migration/migration.service.js
- src/migration/migrationRules.js
- src/south/Modbus/Modbus.class.js
- src/south/Modbus/Modbus.class.spec.js
- src/south/Modbus/Modbus.schema.jsx
This allow to do swapping operations on retreived data. In order to read correctly data from specific modbus PLCs, 3 swapping operations are implemented in this PR :
- swapBytesinWords : Swap Bytes (8 bits) in Words (16 bits) 
- Example : 0101 0001 => 0001 0101
- swapWordsInDWords : Swap Words (16 bits) in DWords (32 bits)
- Example : 0101 0001 1110 0110 => 1110 0110 0101 0001
- swapDWords : Swap DWords in 64 bits
- Example : 0101 0001 1110 0110 0111 1001 1100 0011 => 0111 1001 1100 0011 1110 0110 0101 0001
> feat(south-modbus): Add possibility to do swapping operation (ON TOP OFF #1131)

- src/client/Health/__snapshots__/Health.spec.jsx.snap
- src/client/Health/__snapshots__/Overview.spec.jsx.snap
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/__snapshots__/South.spec.jsx.snap
- src/south/ADS/ADS.class.js
- src/south/ADS/ADS.class.spec.js
- src/south/ADS/ADS.schema.jsx
- tests/testConfig.js
This feature allows the user to specify which fields (separated by commas) of a struct data type to take into account.
The field will be added at the end of the pointId.
The "*" wildcard allows the user to select all fields of a structure. Structures not specified in the settings will be ignored, even if a point of that structure type is requested. In this case a debug message is shown in the logger.
> feat(south-ads): structure filter

- src/engine/Cache.class.js
- src/south/ADS/ADS.class.spec.js
- src/south/ProtocolHandler.class.js
Debounce: when a protocol receives many calls within a second, the engine is called multiple times (i.e. causing sqlite to be called inefficiently). This was causing an issue for a customer having several hundreds calls per second with a MQTT source. 
This PR proposes to group all calls within 300ms or below 250 values to be buffered and grouped into a single call to the engine. The 300ms/250 are now hard coded values but we may consider to expose them to the UI. 
Note that a single value will be delayed by 300ms before being sent to the engine.
> Cache and debounce

- src/client/South/ConfigurePoints.jsx
- src/client/South/ConfigurePoints.spec.jsx
- src/client/components/OIbForm/OIbScanMode.jsx
- src/south/OPCHDA/OPCHDA.schema.jsx
The `reverseIndex` is not a good approach, as the ids in the filtered list are not the same (there are fewer items) so the deletion and update will operate with a wrong id.
Solved it by using a virtual index on the frontend side which is constant even in the filtered list ensuring that the chosen point will be edited or removed.
Solves #1380
> fix(points-filter): Fix "remove" and "edit" on filtered point list

- src/engine/Cache.class.js
- src/engine/Engine.class.js
- src/services/database.service.js
- src/services/queue.class.js
This PR fix the following issue : 
-Step 1 : In FolderScanner, when preserve file is deactivated, the file should be moved
-Step 2 : In Cache, when we move file from a remote disk, we copy it instead
In this step 2, the promise was resolved before the copy finished. I've fixed that by using fs/promises (as we do elsewhere in the code since v2.0) in the cache to avoid out of scope resolve. 
I've also corrected some javadoc in the database.service.js to use it as a typescript-like feature in some IDEs
> fix(cache): fix file copy from remote disk when preserve file is disabled and switch to fs/promises

- .pkg.json
The better-sqlite3 package has several .node files (one per platform) and they do not all end with .node. The executable could not work on macos.
> fix(deps): fix package dependency in executable bundler

- src/server/controllers/logController.js
Logs were properly sent to the loki instance through another OIBus, but the first OIBus received errors because the ctx.ok() was not called. The error was 'hidden' in the console of the first OIBus to avoid a bad loop of logs if the logger was called.
> fix(logs): fix loki addLogs engine method with koa ctx

- src/engine/cache/file-cache.js
- src/engine/cache/file-cache.spec.js
- src/north/north-connector.js
A fix still need to be done on the way the request service (axios or fetch) manage the readStream that can lock a file in a cache while OIBus is running, but this PR fix the lock on one specific file when the north read the cache directory
> fix(north): fix file cache stat eperm error

- src/service/database.service.js
- src/service/database.service.spec.js
I've used the node-os-utils to keep track of the CPU usage. However, during the sqlite reading duration, the cpu usage did not log anything because the main thread was busy with sqlite. 
The test cache database has a size of 6Go (approximately 60 000 000 values).
Here we have the output without the fix:
```
2022-10-26T15:10:32.161Z || CPU:  11.06
2022-10-26T15:10:32.664Z || CPU:  7.96
2022-10-26T15:10:33.163Z || CPU:  12.89
2022-10-26T15:10:33.665Z || CPU:  14.16
2022-10-26T15:10:34.165Z || CPU:  8.14
2022-10-26T15:10:34.667Z || CPU:  7.59
2022-10-26T15:10:35.166Z || CPU:  6.36
2022-10-26T15:10:37.222Z || CPU:  16.58
2022-10-26T15:10:37.223Z || CPU:  19.16
retrieve: 3.747s
North Console sent 10000 values.
remove: 12.186ms
2022-10-26T15:10:40.983Z || CPU:  19.42
```
And with the fix:
``` …
```
> fix(cache): improve perf on values query in sqlite cache

- src/migration/migration-rules.js
- src/service/cache/file-cache.service.js
- src/service/cache/file-cache.service.spec.js
The migration of a 8,19GB outputs 6GB of files (6000 files). My guess is that the database stores uri encoded values where the new cache store regular JSON, reducing the size of the string stored. Such a migration takes 60s approximately on Mac M1.
With many files (~6000), OIBus initialisation takes some time (5/10s on Mac) at full CPU usage because the files are parsed to count the number of values.
> fix(cache): migrate values cache and file errors folder

- src/frontend/north/__snapshots__/configure-north.spec.jsx.snap
- src/frontend/north/form/__snapshots__/north-form.spec.jsx.snap
- src/frontend/north/form/north-form.jsx
- src/frontend/north/form/north.validation.js
- src/migration/migration-rules.js
- src/migration/migration.service.js
- src/service/cache/file-cache.service.js
- src/service/cache/file-cache.service.spec.js
- src/service/cache/value-cache.service.js
- src/service/cache/value-cache.service.spec.js
- src/service/utils.js
I need to test deeper (unit test and runtime tests) but with a quick local fix and test, here is the logic :
- When starting, file and value caches get the whole cache size (including error folders)
- Every send method finish by retrieving again the whole cache size (including error folders), updating the current size
- When caching, the cache size (as a class variable for value/fileCache) is check : if it exceeds the maxSize settings, the values/files will be discarded
> feat(cache): add a max size limit

- frontend/src/app/shared/box/box.component.scss
- frontend/src/app/shared/box/box.component.ts
change :
const emptyDivElements = contentElement.querySelectorAll('div:empty');
for :
const emptyDivElements = contentElement.querySelectorAll('div');
Thanks to this change, the for loop no longer searches for empty divs, but for divs with a length of 0.
Add new class and new const in oib-box.
Now the for loop detects the oib-grey-container class and removes the padding according to its position in oib-box.
I think all the bugs about oib-box and its padding have disappeared.
> fix(styles): fix padding bug

- frontend/angular.json
- frontend/src/app/shared/notification/notification.component.scss
- frontend/src/styles.scss
Looks like it works OK: as Highcharts is not used here, we don't run into the CLI issue we had on OiA
I ran into https://github.com/angular/angular-cli/issues/26339 as for OiA
So I'll revert to the SCSS import when the related issue is fixed (the workaround is good enough for now)
> chore: use application builder

- backend/src/web-server/controllers/validators/joi.validator.ts
Closes: #3080 
Note:
The issue occurred because `.optional()` does not treat empty strings as unset: https://github.com/hapijs/joi/issues/482
> fix(backend): Fix validation of optional items from csv

- frontend/src/app/auth/login/login.component.ts
- frontend/src/app/engine/edit-certificate-modal/edit-certificate-modal.component.ts
- frontend/src/app/engine/edit-engine/edit-engine.component.ts
- frontend/src/app/engine/edit-ip-filter-modal/edit-ip-filter-modal.component.ts
- frontend/src/app/engine/edit-scan-mode-modal/edit-scan-mode-modal.component.ts
- frontend/src/app/engine/oia-module/oia-module.component.ts
- frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.ts
- frontend/src/app/history-query/create-history-query-modal/create-history-query-modal.component.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/history-query/history-query-list.component.ts
- frontend/src/app/logs/logs.component.ts
- frontend/src/app/north/create-north-subscription-modal/create-north-subscription-modal.component.ts
- frontend/src/app/north/north-list.component.ts
- frontend/src/app/shared/datetimepicker/datetimepicker.component.ts
- frontend/src/app/shared/form/oib-scan-mode/oib-scan-mode.component.ts
- frontend/src/app/shared/multi-select/multi-select.component.spec.ts
- frontend/src/app/shared/save-button/save-button.component.spec.ts
- frontend/src/app/south/south-items/south-items.component.ts
- frontend/src/app/south/south-list.component.ts
- frontend/src/app/user-settings/change-password-modal/change-password-modal.component.ts
- frontend/src/app/user-settings/edit-user-settings/edit-user-settings.component.ts
- frontend/tsconfig.json
CLI v18.1 will no longer generates projects that use `useDefineForClassFields` so let's try to keep our codebase similar to the new defaults.
> chore: remove useDefineForClassFields

- backend/src/engine/data-stream-engine.spec.ts
- backend/src/engine/data-stream-engine.ts
- backend/src/engine/history-query-engine.ts
- backend/src/engine/history-query.ts
- backend/src/service/history-query.service.ts
- backend/src/service/north.service.spec.ts
- backend/src/service/north.service.ts
- backend/src/service/oibus.service.ts
- backend/src/service/south.service.spec.ts
- backend/src/service/south.service.ts
- backend/src/tests/__mocks__/service/history-query-service.mock.ts
Fixes issues regarding to folder creation
Note: I've added an additional `runHistoryQuery` method, which is kind of not needed in the way `runSouth` and `runNorth` are, but this way the creation and the way folders are managed are the same for every type of entity.
> fix(backend): Fix folder creation for North/South Connectors and HistoryQuery

- backend/src/engine/history-query.spec.ts
- backend/src/engine/history-query.ts
- backend/src/south/south-connector.spec.ts
- backend/src/south/south-connector.ts
- backend/src/tests/utils/test-data.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.ts
- fixes south metrics so it keeps track of the progress of the full interval
- fixes issues caused by metrics event order
- adds frontend functionality to restart history query after finish
Fixes: #3512
> fix(backend,frontend): Fix history query metrics

- backend/shared/model/form.model.ts
- backend/src/south/south-mssql/manifest.ts
- backend/src/south/south-mysql/manifest.ts
- backend/src/south/south-odbc/manifest.ts
- backend/src/south/south-oledb/manifest.ts
- backend/src/south/south-oracle/manifest.ts
- backend/src/south/south-postgresql/manifest.ts
- backend/src/south/south-slims/manifest.ts
- backend/src/south/south-sqlite/manifest.ts
- backend/src/web-server/controllers/validators/joi.validator.spec.ts
- backend/src/web-server/controllers/validators/joi.validator.ts
- frontend/src/app/shared/default-validation-errors/default-validation-errors.component.html
- frontend/src/app/shared/form-utils.spec.ts
- frontend/src/app/shared/form-utils.ts
- frontend/src/app/shared/form/form.component.html
- frontend/src/app/shared/form/oib-form-array/oib-array.component.html
- frontend/src/app/shared/validators.spec.ts
- frontend/src/app/shared/validators.ts
- frontend/src/i18n/en.json
No validation for only one true reference field
No validation for unique field name
Only one true reference field validation
Unique field name validation
Closes #3754
> Allow only one reference field#3754
