- src/engine/Cache.class.js
- src/engine/Engine.class.js
> Issue #972: Initialize Cache in safe mode

- src/client/Engine/ScanModes.spec.jsx
- src/client/Engine/__snapshots__/Engine.spec.jsx.snap
- src/client/Engine/__snapshots__/ScanModes.spec.jsx.snap
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/__snapshots__/ConfigurePoints.spec.jsx.snap
- src/client/components/OIbForm/OIbCron.jsx
- src/client/components/OIbForm/OIbCron.spec.jsx
- src/client/components/OIbForm/__snapshots__/OIbCron.spec.jsx.snap
- src/config/defaultConfig.json
- src/migration/migration.service.js
- src/migration/migrationRules.js
- tests/testConfig.js
ScanMode should not offer the mode "listen" anymore as it is automatically created #964
> Remove listen#964

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/__snapshots__/ConfigureProtocol.spec.jsx.snap
- src/services/validation.service.js
- src/south/OPCHDA/OPCHDA.schema.jsx
- src/south/OPCUA/OPCUA.schema.jsx
fix(south): handled if val is null; in path.basename(val) val is required.
Fixed error on OPCHDA.
Increased width on Scan Groups in OPCUA and OPCHDA . Increased width in OPCUA settings.
#1020
> Opcua settings display#1020

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/south/SQLDbToFile/SQLDbToFile.schema.jsx
fix(south-sqldbtofile): Added unit for connection and request timeout #983
> fix(south-sqldbtofile): Added unit for connection and request timeout.

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/migration/migration.service.js
- src/migration/migrationRules.js
- src/south/MQTT/MQTT.class.js
- src/south/MQTT/MQTT.class.spec.js
- src/south/MQTT/MQTT.schema.jsx
> South mqtt persistent connection#1021

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/south/OPCUA/OPCUA.class.js
- src/south/OPCUA/OPCUA.class.spec.js
- src/south/OPCUA/OPCUA.schema.jsx
> feat(south-opcua): opcua user/pass authentication

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/engine/Cache.class.js
- src/engine/Engine.class.js
- src/services/validation.service.js
- src/south/FolderScanner/FolderScanner.class.js
- src/south/FolderScanner/FolderScanner.schema.jsx
> feat(folderscanner): improve folderscanner help and log messages

- src/client/Health/__snapshots__/Health.spec.jsx.snap
- src/client/Health/__snapshots__/Overview.spec.jsx.snap
- src/client/South/Form/South.validation.spec.js
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/Protocols.jsx
- src/client/South/__snapshots__/NewDataSourceRow.spec.jsx.snap
- src/client/South/__snapshots__/South.spec.jsx.snap
- src/engine/Engine.class.js
- src/migration/migration.service.js
- src/migration/migrationRules.js
- src/south/OPCUA_DA/OPCUA_DA.class.js
- src/south/OPCUA_DA/OPCUA_DA.class.spec.js
- src/south/OPCUA_DA/OPCUA_DA.schema.jsx
- src/south/OPCUA_DA/OPCUA_DA.schema.spec.js
- src/south/OPCUA_HA/OPCUA_HA.class.js
- src/south/OPCUA_HA/OPCUA_HA.class.spec.js
- src/south/OPCUA_HA/OPCUA_HA.schema.jsx
- src/south/OPCUA_HA/OPCUA_HA.schema.spec.js
- tests/testConfig.js
> Opcua da#1054

- src/client/South/Form/SouthForm.jsx
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/components/OIbForm/OIbInteger.jsx
- src/client/components/OIbForm/OIbPassword.jsx
- src/client/components/OIbForm/OIbText.jsx
- src/south/SQLDbToFile/SQLDbToFile.class.js
- src/south/SQLDbToFile/SQLDbToFile.class.spec.js
- src/south/SQLDbToFile/SQLDbToFile.schema.jsx
- tests/testConfig.js
This is a Work In Progress PR : the front still need to be improved to display only the appropriate settings depending on the selected driver.
For example : 
-sqlite driver only has databasePath and no host/port etc
-mssql has host, port, domain...
-etc
> feat(south-sqldbtofile): add sqlite driver for local sqlite db file

- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/south/SQLDbToFile/SQLDbToFile.schema.jsx
> fix(south-sqldbtofile): Update documentation for readonly user access

- src/client/Health/NodeView.jsx
- src/client/TopHeader.jsx
- src/client/style/oi.css
Safe mode warning added based on request: #1215
Please check and let me know if anything needs to be changed. Not sure if the blinking warning makes more sense to be in the red engine block, right after the "Engine 1.1.0" title. 
https://user-images.githubusercontent.com/47381370/119644778-f0ec0880-be25-11eb-9681-47a329cda7d3.mov
> feat(overview): Safe mode status warning.

- src/client/South/ConfigurePoints.jsx
- src/client/South/__snapshots__/ConfigurePoints.spec.jsx.snap
- src/client/components/OIbForm/OIbScanMode.jsx
- src/client/components/OIbForm/OIbScanMode.spec.jsx
- src/client/components/OIbForm/OIbTable.spec.jsx
- src/south/OPCHDA/OPCHDA.schema.jsx
- src/south/OPCUA_HA/OPCUA_HA.schema.jsx
> Scan group protocols should only allow scan modes set in a scan group as option

- src/client/South/ConfigurePoints.jsx
- src/client/South/Form/South.validation.js
- src/client/components/OIbForm/OIbText.jsx
- src/south/MQTT/MQTT.schema.jsx
> feat(points): Error on MQTT duplicated points.

- src/client/Health/NodeView.jsx
> fix(ui): fix overllaping text in home screen #1256

- src/client/Engine/AliveSignal.jsx
- src/client/South/Form/SouthForm.jsx
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/StatusButton.jsx
- src/client/South/__snapshots__/ConfigureProtocol.spec.jsx.snap
> fix(ui): Enabled-Disabled & Status-Button 

- src/client/TopHeader.jsx
> fix(ui): warning-user-default-password #1275

- src/migration/migrationRules.js
As we have discussed, this is the first strategy of resolving this problem
> feature(protocols-attribute): missing points attribute #1286

- src/client/Engine/Engine.validation.js
- src/client/Engine/ScanModes.jsx
- src/client/Engine/ScanModes.spec.jsx
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/components/OIbForm/__snapshots__/OIbInteger.spec.jsx.snap
- src/services/validation.service.js
> fix(scan-mode): Default new scan mode type changed to “every”

- src/client/Engine/ExternalSources.spec.jsx
- src/client/Engine/Filters.spec.jsx
- src/client/Engine/Proxies.spec.jsx
- src/client/Engine/ScanModes.spec.jsx
- src/client/North/Form/SubscribedTo.spec.jsx
- src/client/North/North.spec.jsx
- src/client/South/ConfigurePoints.spec.jsx
- src/client/South/South.spec.jsx
- src/client/components/OIbForm/OIbTable.spec.jsx
- src/client/components/table/TableRows.jsx
> feat(delete): added confirmation before deleting row(entry) in any table

- src/north/filewriter/FileWriter.class.spec.js
> fix(test): unit test for FileWriter 

- src/client/South/ConfigurePoints.jsx
- src/client/South/Form/South.validation.js
> fix(points): Show error message if unintended spaces are present in point id

- src/client/North/Form/__snapshots__/NorthForm.spec.jsx.snap
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/migration/migration.service.js
- src/migration/migrationRules.js
- src/north/mqttnorth/MQTTNorth.class.js
- src/north/mqttnorth/MQTTNorth.class.spec.js
- src/north/mqttnorth/MQTTNorth.schema.jsx
- src/south/MQTT/MQTT.class.js
- src/south/MQTT/MQTT.class.spec.js
- src/south/MQTT/MQTT.schema.jsx
- tests/testConfig.js
new branch from develop including proposal code to allow mqtts authenticate with certificates for South connector MQTT and North connector MQTTNorth
> feat(mqtt): allow mqtts authenticate with certificates

- src/south/Modbus/Modbus.class.js
- src/south/Modbus/Modbus.class.spec.js
> fix(modbus): fix swap bug on bytes when number is UINT32

- src/engine/Engine.class.js
- src/north/filewriter/FileWriter.class.js
- src/north/filewriter/FileWriter.class.spec.js
- src/south/FolderScanner/FolderScanner.class.js
- src/south/FolderScanner/FolderScanner.class.spec.js
- src/south/ProtocolHandler.class.js
PR based on master branch - bug to be fix asap.
This fix is under tests on a Windows VM to fix a runtime exception which occurs after a while.
> fix(FolderScanner): adapt file access with async to fix folder scanner lock bug

- src/client/Home/NodeView.jsx
- src/client/style/oi.css
Solves #1549  and #1551 
The tooltip looks like this: 
Popover issue:
> fix(home-ui): Add tooltip, fix popover issue

- src/client/Engine/Logging/ConsoleLogging.jsx
- src/client/Engine/Logging/FileLogging.jsx
- src/client/Engine/Logging/Logging.jsx
- src/client/Engine/Logging/LokiLogging.jsx
- src/client/Engine/Logging/SqliteLogging.jsx
- src/client/Engine/Logging/__snapshots__/ConsoleLogging.spec.jsx.snap
- src/client/Engine/Logging/__snapshots__/FileLogging.spec.jsx.snap
- src/client/Engine/Logging/__snapshots__/Logging.spec.jsx.snap
- src/client/Engine/Logging/__snapshots__/LokiLogging.spec.jsx.snap
- src/client/Engine/Logging/__snapshots__/SqliteLogging.spec.jsx.snap
- src/client/Engine/__snapshots__/Engine.spec.jsx.snap
- src/client/North/Form/__snapshots__/NorthForm.spec.jsx.snap
- src/client/North/__snapshots__/ConfigureApi.spec.jsx.snap
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/__snapshots__/ConfigureProtocol.spec.jsx.snap
- src/client/components/OIbForm/OIbLogLevel.jsx
- src/engine/Cache.class.js
- src/engine/logger/Logger.class.js
- src/engine/logger/SqliteLoggerTransport.class.js
- src/migration/migrationRules.js
- src/services/request/AxiosRequest.class.spec.js
- src/services/request/BaseRequest.class.js
- src/services/request/BaseRequest.class.spec.js
- src/services/request/FetchRequest.class.spec.js
@jfhenon I've also made some changes that may fix the logger timeout issue on closing oibus. Can you please take a look and test it on your environment ?
> fix(logs): change silly option to trace option (used in pino and loki)

- package-lock.json
- package.json
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/components/OIbForm/OIbTextArea.jsx
- src/client/components/OIbForm/__snapshots__/OIbTextArea.spec.jsx.snap
- src/south/SQLDbToFile/SQLDbToFile.schema.jsx
- webpack.config.js
Using tab works properly. When the query is too long, we can scroll the query.
> feat(sql): use monaco editor and highlight sql syntax in sql query

- src/client/Home/EngineMenu.jsx
- src/client/Home/NodeView.jsx
- src/client/Home/NorthMenu.jsx
- src/client/Home/SouthMenu.jsx
> fix(ui): Fix home page dropdown overlap problem

- src/client/Home/NodeView.jsx
> fix(ui): Remove opacity from node background keeping the same color

- src/client/Home/NewNorth.jsx
- src/client/Home/NewSouth.jsx
- src/client/style/oi.css
- src/engine/BaseEngine.class.js
- src/engine/OIBusEngine.class.js
> fix(ui): reorder connectors and improve css when adding connectors

- src/client/Engine/__snapshots__/Caching.spec.jsx.snap
- src/client/Engine/__snapshots__/Engine.spec.jsx.snap
- src/client/Engine/__snapshots__/HealthSignal.spec.jsx.snap
- src/client/HistoryQuery/Form/__snapshots__/HistoryQueryForm.spec.jsx.snap
- src/client/North/Form/__snapshots__/NorthForm.spec.jsx.snap
- src/client/North/__snapshots__/ConfigureApi.spec.jsx.snap
- src/client/South/Form/__snapshots__/SouthForm.spec.jsx.snap
- src/client/South/__snapshots__/ConfigureProtocol.spec.jsx.snap
- src/client/components/OIbForm/OIbCheckBox.jsx
- src/client/components/OIbForm/__snapshots__/OIbCheckBox.spec.jsx.snap
can be changed later if reactstrap fix the issue
> fix(Component): change props to underlying classname to remove message

- src/HistoryQuery/HistoryQuery.class.js
- src/engine/cache/ValueCache.class.js
- src/north/NorthConnector.class.js
- src/north/NorthConnector.class.spec.js
> cache-groupe-count

- src/HistoryQuery/HistoryQuery.class.js
- src/HistoryQuery/HistoryQueryEngine.class.js
- src/client/North/Form/North.validation.js
- src/client/North/Form/NorthForm.jsx
- src/client/North/Form/__snapshots__/NorthForm.spec.jsx.snap
- src/client/North/__snapshots__/ConfigureApi.spec.jsx.snap
- src/engine/BaseEngine.class.js
- src/engine/OIBusEngine.class.js
- src/engine/cache/FileCache.class.js
- src/migration/migrationRules.js
- src/north/AmazonS3/AmazonS3.class.js
- src/north/NorthConnector.class.js
- src/north/NorthConnector.class.spec.js
- src/north/OIAnalytics/OIAnalytics.class.js
- src/north/OIAnalytics/OIAnalytics.class.spec.js
- src/north/OIConnect/OIConnect.class.js
- src/north/OIConnect/OIConnect.class.spec.js
- src/services/request/BaseRequest.class.js
- src/services/request/BaseRequest.class.spec.js
- src/services/status.service.class.js
- src/south/SouthConnector.class.js
The retry logic has been moved to NorthConnector, so I removed the logic from BaseRequest.
> fix(north): fix North retry error and catch init/connect error

- src/services/database.class.spec.js
- src/services/database.service.js
Prepare paginate logs #1809 on the backend
The filtering for text content is now possible on the backend. It was previously done on the client side with all logs.
Still to implement by @Reloflex: 
- A pagination component to navigate between page
- A form as shown in #1809
- A rework of the displayed logs
- A hint that now logs match the query if no log is retrieved
> paginated-logs-backend

- src/services/request/AxiosRequest.class.js
- src/services/request/AxiosRequest.class.spec.js
- src/services/request/FetchRequest.class.js
- src/services/request/FetchRequest.class.spec.js
- src/south/Modbus/Modbus.class.js
- src/south/Modbus/Modbus.class.spec.js
- src/south/SouthConnector.class.js
> fix-request-error

- .github/renovate.json
- .github/workflows/codeql.yml
- src/south/south-rest/south-rest.js
> chore(code): add GitHub CodeQL quality tool

- src/service/request/axios-request.js
- src/service/request/axios-request.spec.js
- src/service/request/base-request.js
- src/service/request/base-request.spec.js
- src/service/request/fetch-request.js
- src/service/request/fetch-request.spec.js
- src/service/utils.js
- src/service/utils.spec.js
> readstream-http-request

- .github/actions/setup_backend_environment/action.yml
- .github/actions/setup_frontend_environment/action.yml
- .github/actions/unit_tests/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- frontend/package.json
> Angular: add tests to CI

- backend/model/proxy.model.ts
- backend/repository/proxy.repository.ts
- backend/web-server/controllers/api.controller.ts
- backend/web-server/koa.ts
- backend/web-server/routes/index.js
> story-angular-engine-endpoints

- frontend/src/app/history-query/create-history-query-modal/create-history-query-modal.component.html
- frontend/src/app/history-query/create-history-query-modal/create-history-query-modal.component.spec.ts
- frontend/src/app/history-query/create-history-query-modal/create-history-query-modal.component.ts
- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/app/history-query/history-query-list.component.spec.ts
- frontend/src/app/history-query/history-query-list.component.ts
- frontend/src/app/model/history-query.model.ts
- frontend/src/app/model/north-connector.model.ts
- frontend/src/app/model/south-connector.model.ts
- frontend/src/app/navbar/navbar.component.html
- frontend/src/app/navbar/navbar.component.spec.ts
- frontend/src/app/north/create-north-connector-modal/create-north-connector-modal.component.spec.ts
- frontend/src/app/services/history-query.service.spec.ts
- frontend/src/app/services/history-query.service.ts
- frontend/src/app/south/create-south-connector-modal/create-south-connector-modal.component.spec.ts
- frontend/src/i18n/en.json
> Story angular history query frontend list

- frontend/src/app/app.routes.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/history-query/history-query-display/history-query-display.component.html
- frontend/src/app/history-query/history-query-display/history-query-display.component.spec.ts
- frontend/src/app/history-query/history-query-display/history-query-display.component.ts
> Story angular history query edit

- backend/src/engine/history-query-engine.spec.ts
- backend/src/engine/history-query-engine.ts
- backend/src/repository/history-query.repository.spec.ts
- backend/src/repository/history-query.repository.ts
- backend/src/service/history-query.service.spec.ts
- backend/src/service/history-query.service.ts
- backend/src/service/reload.service.spec.ts
- backend/src/service/reload.service.ts
- backend/src/tests/__mocks__/history-query-service.mock.ts
- backend/src/tests/__mocks__/reload-service.mock.ts
- backend/src/tests/__mocks__/repository-service.mock.ts
- backend/src/web-server/controllers/history-query.controller.spec.ts
- backend/src/web-server/controllers/history-query.controller.ts
- backend/src/web-server/routes/index.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/services/history-query.service.spec.ts
- frontend/src/app/services/history-query.service.ts
- shared/model/history-query.model.ts
> history-query-start

- backend/src/tests/__mocks__/repository-service.mock.ts
- backend/src/web-server/controllers/history-query.controller.spec.ts
- backend/src/web-server/controllers/history-query.controller.ts
- backend/src/web-server/routes/index.ts
- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.html
- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.spec.ts
- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.html
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.spec.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/app/history-query/history-query-list.component.spec.ts
- frontend/src/app/history-query/history-query-list.component.ts
- frontend/src/app/north/north-detail/north-detail.component.html
- frontend/src/app/services/history-query.service.spec.ts
- frontend/src/app/services/history-query.service.ts
- frontend/src/app/services/south-connector.service.spec.ts
- frontend/src/app/services/south-connector.service.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.spec.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.ts
- frontend/src/i18n/en.json
> history-query-design

- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/north/edit-north/edit-north.component.html
- frontend/src/app/shared/form/form.component.html
- frontend/src/app/shared/form/form.component.spec.ts
- frontend/src/app/shared/form/form.component.ts
- frontend/src/app/shared/form/oib-form-array/edit-element/edit-element.component.html
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.html
- frontend/src/app/south/edit-south/edit-south.component.html
Array with grouped controls is now created once at component init
> fix form rendering

- backend/src/service/cache/file-cache.service.spec.ts
- backend/src/service/cache/file-cache.service.ts
- frontend/src/app/north/explore-cache/explore-cache.component.html
> Fix: Retry files (from error) do not update the queue

- backend/src/engine/oibus-engine.spec.ts
- backend/src/engine/oibus-engine.ts
- backend/src/north/north-connector.spec.ts
- backend/src/north/north-connector.ts
- backend/src/service/cache/archive.service.spec.ts
- backend/src/service/cache/archive.service.ts
- backend/src/service/cache/file-cache.service.spec.ts
- backend/src/service/cache/file-cache.service.ts
- backend/src/tests/__mocks__/archive-service.mock.ts
- backend/src/tests/__mocks__/file-cache-service.mock.ts
- backend/src/tests/__mocks__/reload-service.mock.ts
- backend/src/web-server/controllers/north-connector.controller.spec.ts
- backend/src/web-server/controllers/north-connector.controller.ts
- backend/src/web-server/routes/index.ts
- frontend/src/app/north/explore-cache/archive-files/archive-files.component.html
- frontend/src/app/north/explore-cache/archive-files/archive-files.component.spec.ts
- frontend/src/app/north/explore-cache/archive-files/archive-files.component.ts
- frontend/src/app/north/explore-cache/error-files/error-files.component.ts
- frontend/src/app/north/explore-cache/explore-cache.component.html
- frontend/src/app/north/explore-cache/explore-cache.component.spec.ts
- frontend/src/app/north/explore-cache/explore-cache.component.ts
- frontend/src/app/services/north-connector.service.spec.ts
- frontend/src/app/services/north-connector.service.ts
- frontend/src/i18n/en.json
- shared/model/north-connector.model.ts
> Feature: North archive folder operations

- frontend/src/app/north/explore-cache/archive-files/archive-files.component.html
- frontend/src/app/north/explore-cache/archive-files/archive-files.component.scss
- frontend/src/app/north/explore-cache/archive-files/archive-files.component.ts
- frontend/src/app/north/explore-cache/error-files/error-files.component.html
- frontend/src/app/north/explore-cache/error-files/error-files.component.scss
- frontend/src/app/north/explore-cache/error-files/error-files.component.ts
- frontend/src/app/north/explore-cache/explore-cache.component.html
- frontend/src/styles.scss
Move the checkbox code so as not to encroach on the switch on the north and south edit pages
> fix(styles): checkbox/switch

- frontend/src/app/north/edit-north/edit-north.component.html
- frontend/src/app/north/edit-north/edit-north.component.ts
- frontend/src/app/north/north-detail/north-detail.component.html
- frontend/src/app/north/north-detail/north-detail.component.ts
- frontend/src/app/services/north-connector.service.spec.ts
- frontend/src/app/services/north-connector.service.ts
- frontend/src/i18n/en.json
> feat(north): Add test connection button

- backend/src/north/north-console/north-console.spec.ts
- backend/src/north/north-console/north-console.ts
> Feature: Add NorthConsole connection test

- backend/src/web-server/controllers/south-connector.controller.spec.ts
- backend/src/web-server/controllers/south-connector.controller.ts
- frontend/src/app/services/south-connector.service.spec.ts
- frontend/src/app/services/south-connector.service.ts
- frontend/src/app/south/south-items/south-items.component.ts
> fix(south-items): Fix import items after deletion in edit mode

- backend/src/tests/__mocks__/north-service.mock.ts
- backend/src/web-server/controllers/north-connector.controller.spec.ts
- backend/src/web-server/controllers/north-connector.controller.ts
- backend/src/web-server/controllers/south-connector.controller.spec.ts
- backend/src/web-server/controllers/south-connector.controller.ts
- backend/src/web-server/routes/index.ts
Applies the fixes done to the importing and exporting of south items (#2826 and #2838) for north items
> Fix(north): Fix import / export north items

- frontend/src/app/home/home.component.html
adaptation of align between metrics and north/south
> fix(styles):north/south

- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/app/history-query/history-query-list.component.spec.ts
- frontend/src/styles.scss
resize history query table + change "->" for "fa-arrow-right"
> fix(styles):history query

- frontend/src/app/logs/logs.component.html
- frontend/src/app/logs/logs.component.scss
- frontend/src/app/logs/logs.component.spec.ts
resize logs table + change badge pill for color text
> fix(styles): logs

- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/app/history-query/history-query-list.component.ts
- frontend/src/app/north/north-list.component.html
- frontend/src/app/north/north-list.component.ts
- frontend/src/app/shared/legend/legend.component.html
- frontend/src/app/shared/legend/legend.component.scss
- frontend/src/app/shared/legend/legend.component.spec.ts
- frontend/src/app/shared/legend/legend.component.ts
- frontend/src/app/south/south-list.component.html
- frontend/src/app/south/south-list.component.ts
- frontend/src/styles.scss
add pellet to the history table
creation of css class for pellet
import ngClass and CommenModule in the composant
+ edit ERRONED > ERRORED
> fix(styles): History query list

- backend/src/south/south-mssql/south-mssql.spec.ts
- backend/src/south/south-mssql/south-mssql.ts
- backend/src/south/south-mysql/south-mysql.spec.ts
- backend/src/south/south-mysql/south-mysql.ts
- backend/src/south/south-oracle/south-oracle.spec.ts
- backend/src/south/south-oracle/south-oracle.ts
- backend/src/south/south-postgresql/south-postgresql.spec.ts
- backend/src/south/south-postgresql/south-postgresql.ts
- backend/src/south/south-sqlite/south-sqlite.spec.ts
- backend/src/south/south-sqlite/south-sqlite.ts
> fix(south): Fix SQL queries to only count tables

- frontend/src/app/history-query/history-query-list.component.ts
- frontend/src/app/logs/logs.component.html
- frontend/src/app/logs/logs.component.spec.ts
- frontend/src/app/logs/logs.component.ts
- frontend/src/styles.scss
+ change dark green to blue in historyQuery table and legend
> style(logs): add legend and dot for differentiate level in logs table

- frontend/src/app/north/explore-cache/explore-cache.component.html
fix(cache): change the margin between : oib-cache-files / oib-error-files / oib-archive-files
> fix(cache): change the margin between cache files

- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/app/history-query/history-query-list.component.spec.ts
> fix(history-query): Add history query duplicate button

- backend/src/web-server/controllers/history-query.controller.spec.ts
- backend/src/web-server/controllers/history-query.controller.ts
- backend/src/web-server/routes/index.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.html
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.spec.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.ts
- frontend/src/app/services/history-query.service.spec.ts
- frontend/src/app/services/history-query.service.ts
- frontend/src/app/shared/test-connection-result-modal/test-connection-result-modal.component.spec.ts
- frontend/src/app/shared/test-connection-result-modal/test-connection-result-modal.component.ts
> Feature: Add connector test to history queries

- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/south/south-items/south-items.component.html
- frontend/src/app/south/south-items/south-items.component.ts
> fix(history-query): Paginate south items

- frontend/src/app/engine/certificate-list/certificate-list.component.html
- frontend/src/app/engine/external-source-list/external-source-list.component.html
- frontend/src/app/engine/ip-filter-list/ip-filter-list.component.html
- frontend/src/app/engine/scan-mode-list/scan-mode-list.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/north/north-subscriptions/north-subscriptions.component.html
- frontend/src/app/south/south-items/south-items.component.html
- frontend/src/app/south/south-items/south-items.component.ts
> feat(frontend): Display number of items in tables

- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.spec.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.ts
- frontend/src/i18n/en.json
> fix(south): Fix duplicating south items

- backend/src/engine/history-query.spec.ts
- backend/src/engine/history-query.ts
- backend/src/service/history-metrics.service.spec.ts
- backend/src/service/history-metrics.service.ts
- backend/src/service/reload.service.spec.ts
- backend/src/service/reload.service.ts
- backend/src/south/south-connector.spec.ts
- backend/src/south/south-connector.ts
- backend/src/tests/__mocks__/reload-service.mock.ts
- backend/src/web-server/controllers/history-query.controller.spec.ts
- backend/src/web-server/controllers/history-query.controller.ts
- frontend/proxy.conf.mjs
- frontend/src/app/history-query/history-query-detail/history-metrics/history-metrics.component.html
- frontend/src/app/history-query/history-query-detail/history-metrics/history-metrics.component.spec.ts
- frontend/src/app/history-query/history-query-detail/history-metrics/history-metrics.component.ts
- frontend/src/app/history-query/history-query-detail/history-metrics/progressbar/progressbar.component.html
- frontend/src/app/history-query/history-query-detail/history-metrics/progressbar/progressbar.component.scss
- frontend/src/app/history-query/history-query-detail/history-metrics/progressbar/progressbar.component.spec.ts
- frontend/src/app/history-query/history-query-detail/history-metrics/progressbar/progressbar.component.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.html
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.ts
- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/i18n/en.json
- shared/model/engine.model.ts
- shared/model/history-query.model.ts
> History query progress bar#2985

- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-list.component.html
- frontend/src/app/history-query/history-query-list.component.spec.ts
- frontend/src/app/north/north-list.component.html
- frontend/src/app/south/south-detail/south-detail.component.html
- frontend/src/app/south/south-items/south-items.component.html
- frontend/src/app/south/south-list.component.html
- frontend/src/styles.scss
fix cell size / add text-overflow: clip / minimize ("type"/"mode"/"interval") column / define first/last cell size / tooltip
> fix(table): cell size

- backend/src/service/reload.service.spec.ts
- backend/src/service/reload.service.ts
- backend/src/tests/__mocks__/repository-service.mock.ts
- backend/src/tests/__mocks__/south-cache-repository.mock.ts
- backend/src/web-server/controllers/south-connector.controller.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.html
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.ts
- frontend/src/app/south/edit-south/edit-south.component.html
- frontend/src/app/south/edit-south/edit-south.component.ts
- frontend/src/app/south/south-items/south-items.component.ts
- frontend/src/i18n/en.json
> Scan mode fix last max instant#3194

- backend/src/north/north-azure-blob/north-azure-blob.spec.ts
- backend/src/north/north-azure-blob/north-azure-blob.ts
> azure-blob-test

- frontend/src/app/logs/logs.component.ts
> fix(frontend): Fixed auto refreshing logs when the end date is filled or when the page number is other than 0

- backend/src/index.ts
- backend/src/tests/__mocks__/proxy-server.mock.ts
- backend/src/tests/__mocks__/reload-service.mock.ts
- backend/src/web-server/controllers/ip-filter.controller.ts
- backend/src/web-server/middlewares/oibus.ts
- backend/src/web-server/proxy-server.ts
- backend/src/web-server/web-server.ts
> fix(web-server): fix IP filter reloading on change

- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/south/south-items/south-items.component.ts
> duplicate-items

- backend/src/service/reload.service.spec.ts
- backend/src/service/reload.service.ts
> fix: conflict web server and proxy port

- backend/src/service/proxy-agent.spec.ts
- backend/src/service/proxy-agent.ts
- backend/src/web-server/proxy-server.spec.ts
- backend/src/web-server/proxy-server.ts
> Azure blob connection failed#3460

- backend/src/repository/registration.repository.spec.ts
- backend/src/repository/registration.repository.ts
- backend/src/service/oia/registration.service.spec.ts
- backend/src/service/oia/registration.service.ts
- backend/src/tests/__mocks__/registration-service.mock.ts
- backend/src/tests/__mocks__/repository-service.mock.ts
- backend/src/web-server/controllers/registration.controller.spec.ts
- backend/src/web-server/controllers/registration.controller.ts
- backend/src/web-server/routes/index.ts
- frontend/src/app/engine/oia-module/oia-module.component.html
- frontend/src/app/engine/oia-module/oia-module.component.ts
- frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.spec.ts
- frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.ts
- frontend/src/app/services/engine.service.spec.ts
- frontend/src/app/services/engine.service.ts
> fix: add proxy configuration without unregister

- backend/src/web-server/controllers/history-query.controller.spec.ts
- backend/src/web-server/controllers/history-query.controller.ts
- backend/src/web-server/controllers/south-connector.controller.spec.ts
- backend/src/web-server/controllers/south-connector.controller.ts
- backend/src/web-server/routes/index.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.spec.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/services/history-query.service.spec.ts
- frontend/src/app/services/history-query.service.ts
- frontend/src/app/services/south-connector.service.spec.ts
- frontend/src/app/services/south-connector.service.ts
- frontend/src/app/shared/export-item-modal/export-item-modal.component.html
- frontend/src/app/shared/export-item-modal/export-item-modal.component.spec.ts
- frontend/src/app/shared/export-item-modal/export-item-modal.component.ts
- frontend/src/app/shared/import-item-modal/import-item-modal.component.html
- frontend/src/app/shared/import-item-modal/import-item-modal.component.spec.ts
- frontend/src/app/shared/import-item-modal/import-item-modal.component.ts
- frontend/src/app/south/south-items/south-items.component.html
- frontend/src/app/south/south-items/south-items.component.spec.ts
- frontend/src/app/south/south-items/south-items.component.ts
- frontend/src/i18n/en.json
> feat: export items delimiter

- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.spec.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/south/south-items/south-items.component.html
- frontend/src/app/south/south-items/south-items.component.spec.ts
- frontend/src/app/south/south-items/south-items.component.ts
> Sort items#3254

- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/shared/datetimepicker/datetimepicker.component.ts
- frontend/src/app/shared/default-validation-errors/default-validation-errors.component.html
- frontend/src/i18n/en.json
> fix(frontend): Validate that the start and end range is correct

- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.html
- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.spec.ts
- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.html
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.html
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.spec.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.ts
- frontend/src/app/south/edit-south/edit-south.component.html
- frontend/src/app/south/edit-south/edit-south.component.ts
- frontend/src/app/south/south-detail/south-detail.component.html
- frontend/src/app/south/south-detail/south-detail.component.ts
- frontend/src/app/south/south-item-test/south-item-test.component.html
- frontend/src/app/south/south-item-test/south-item-test.component.spec.ts
- frontend/src/app/south/south-item-test/south-item-test.component.ts
- frontend/src/app/south/south-items/south-items.component.ts
> feat(south-items): Add item testing on create pages and improve test coverage

- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.spec.ts
- frontend/src/app/history-query/edit-history-query-item-modal/edit-history-query-item-modal.component.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/history-query/history-query-detail/history-query-detail.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.html
- frontend/src/app/history-query/history-query-items/history-query-items.component.spec.ts
- frontend/src/app/history-query/history-query-items/history-query-items.component.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.spec.ts
- frontend/src/app/south/edit-south-item-modal/edit-south-item-modal.component.ts
- frontend/src/app/south/edit-south/edit-south.component.html
- frontend/src/app/south/edit-south/edit-south.component.ts
- frontend/src/app/south/south-detail/south-detail.component.html
- frontend/src/app/south/south-items/south-items.component.html
- frontend/src/app/south/south-items/south-items.component.spec.ts
- frontend/src/app/south/south-items/south-items.component.ts
> fix(frontend): Fix item management and validation

- frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.html
- frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.spec.ts
- frontend/src/app/engine/oia-module/register-oibus-modal/register-oibus-modal.component.ts
- frontend/src/i18n/en.json
UI before the changes:
UI after the changes:
> Toggle all commands on OIAnalytics registration modal #3995

- frontend/src/app/history-query/import-history-query-items-modal/import-history-query-items-modal.component.html
- frontend/src/app/history-query/import-history-query-items-modal/import-history-query-items-modal.component.scss
- frontend/src/app/history-query/import-history-query-items-modal/import-history-query-items-modal.component.ts
- frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.html
- frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.scss
- frontend/src/app/south/import-south-items-modal/import-south-items-modal.component.ts
UI before the changes:
UI after the changes:
> Item import validation #4032

- frontend/src/app/history-query/edit-history-query/edit-history-query.component.html
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.spec.ts
- frontend/src/app/history-query/edit-history-query/edit-history-query.component.ts
- frontend/src/app/shared/date-range-selector/date-range-selector.component.html
- frontend/src/app/shared/date-range-selector/date-range-selector.component.spec.ts
- frontend/src/app/shared/date-range-selector/date-range-selector.component.ts
- frontend/src/app/south/south-item-test/south-item-test.component.html
- frontend/src/app/south/south-item-test/south-item-test.component.spec.ts
- frontend/src/app/south/south-item-test/south-item-test.component.ts
- frontend/src/i18n/en.json
UI before the changes:
UI after the changes:
> Start and end time presets #3687

- frontend/src/app/engine/transformer-list/edit-transformer-modal/edit-transformer-modal.component.html
- frontend/src/app/engine/transformer-list/edit-transformer-modal/edit-transformer-modal.component.scss
- frontend/src/app/engine/transformer-list/edit-transformer-modal/edit-transformer-modal.component.spec.ts
- frontend/src/app/engine/transformer-list/edit-transformer-modal/edit-transformer-modal.component.ts
- frontend/src/app/shared/form/form-utils.spec.ts
- frontend/src/app/shared/form/form-utils.ts
- frontend/src/app/shared/form/manifest-builder/manifest-attribute-editor-modal/manifest-attribute-editor-modal.component.html
- frontend/src/app/shared/form/manifest-builder/manifest-attribute-editor-modal/manifest-attribute-editor-modal.component.spec.ts
- frontend/src/app/shared/form/manifest-builder/manifest-attribute-editor-modal/manifest-attribute-editor-modal.component.ts
- frontend/src/app/shared/form/manifest-builder/manifest-attributes-array/manifest-attributes-array.component.html
- frontend/src/app/shared/form/manifest-builder/manifest-attributes-array/manifest-attributes-array.component.spec.ts
- frontend/src/app/shared/form/manifest-builder/manifest-attributes-array/manifest-attributes-array.component.ts
- frontend/src/app/shared/form/manifest-builder/manifest-builder.component.html
- frontend/src/app/shared/form/manifest-builder/manifest-builder.component.spec.ts
- frontend/src/app/shared/form/manifest-builder/manifest-builder.component.ts
- frontend/src/i18n/en.json
UI before changes:
UI after changes:
> Custom transformer options form#4084
